name: "Build"

on:
  push:
    branches:
      - dev

jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.increment_version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

        #2 Get Latest Release
      - name: Get Latest Release
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}

      #3 Extract Version
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=v$version" >> $GITHUB_OUTPUT

      #4 Increment Version
      - name: Increment version
        id: increment_version
        run: |
          # Extraire la dernière version publiée et la version du fichier pubspec.yaml
          latest_version="${{ steps.get_latest_release.outputs.release }}"
          extracted_version="${{ steps.extract_version.outputs.VERSION }}"

          new_version=""

          # Extraire X, Y, Z et suffix des deux versions
          if [[ $latest_version =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$ ]]; then
              latest_X="${BASH_REMATCH[1]}"
              latest_Y="${BASH_REMATCH[2]}"
              latest_Z="${BASH_REMATCH[3]}"
              latest_suffix="${BASH_REMATCH[4]}"
          else
              echo "Format de la dernière version publiée invalide: $latest_version"
              exit 1
          fi

          if [[ $extracted_version =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$ ]]; then
              extracted_X="${BASH_REMATCH[1]}"
              extracted_Y="${BASH_REMATCH[2]}"
              extracted_Z="${BASH_REMATCH[3]}"
              extracted_suffix="${BASH_REMATCH[4]}"
          else
              echo "Format de la version extraite invalide: $extracted_version"
              exit 1
          fi

          add_alpha_suffix=false
          if [[ -z "$extracted_suffix" ]] && [ "$extracted_X" -eq 0 ]; then
              add_alpha_suffix=true
          fi

          new_latest_X=$latest_X
          new_latest_Y=$latest_Y
          new_latest_Z=$latest_Z
          new_latest_suffix=$latest_suffix
          new_extracted_X=$extracted_X
          new_extracted_Y=$extracted_Y
          new_extracted_Z=$extracted_Z
          new_extracted_suffix=$extracted_suffix

          is_new_version=false

          if [[ "${{ github.event.head_commit.message }}" == fix* ]]; then
              new_latest_Z=$latest_Z+1
              new_extracted_Z=$extracted_Z+1
              is_new_version=true
          fi

          if [[ "${{ github.event.head_commit.message }}" == feat* ]]; then
              new_latest_Y=$latest_Y+1
              new_extracted_Y=$extracted_Y+1
              is_new_version=true
          fi

          tr_commit=$(echo "${{ github.event.head_commit.message }}" | tr ":" "\n")
          start_commit=${tr_commit[0]}

          if [[ $start_commit == *"!"* ]] || [[ "${{ github.event.head_commit.message }}" == *"BREAKING CHANGE" ]]; then
              new_latest_Y=$latest_X+1
              new_extracted_Y=$extracted_X+1
              new_extracted_suffix=""
              new_latest_suffix=""
              is_new_version=true
          fi

          if [ "$is_new_version" == true ]; then

            # Comparaison des parties de version
            if (( extracted_X > latest_X )) || 
                (( extracted_X == latest_X && extracted_Y > latest_Y )) || 
                (( extracted_X == latest_X && extracted_Y == latest_Y && extracted_Z > latest_Z )); then
                # Utiliser la version extraite si elle est plus grande
                new_version="$extracted_version"
            elif (( extracted_X == latest_X && extracted_Y == latest_Y && extracted_Z == latest_Z )); then
                # Incrémenter Z de la version extraite si elle est égale à la dernière version
                new_Z=$((extracted_Z + 1))
                new_version="v${extracted_X}.${extracted_Y}.${new_Z}${extracted_suffix}"
            else
                # Sinon, incrémenter la dernière version
                new_Z=$((latest_Z + 1))
                new_version="v${latest_X}.${latest_Y}.${new_Z}${latest_suffix}"
                if [[ -z "$latest_suffix" ]] && [ "$latest_X" -eq 0 ]; then
                  add_alpha_suffix=true
                fi          
            fi

            echo "$add_alpha_suffix"

            # Ajouter "-alpha" si nécessaire
            if [[ "$add_alpha_suffix" == true ]]; then
                new_version="${new_version}-alpha"
            fi

          fi

          echo "Nouvelle version: $new_version"
          echo "NEW_VERSION=" >> $GIHUB_OUTPUT
          # echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

  build:
    name: Build & Release
    runs-on: macos-latest
    needs: get_version
    if: ${{ needs.get_version.outputs.version != '' }}

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        #5 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

        #6 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"

        #7 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #8 Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

        #9 Building APK
      - name: Build APK
        run: |
          echo "API_TOKEN=${{ secrets.START_GG_API_TOKEN }}" > .env
          flutter build apk --release

        #10 Building App Bundle (aab)
      - name: Build appBundle
        run: |
          echo "API_TOKEN=${{ secrets.START_GG_API_TOKEN }}" > .env
          flutter build appbundle

        # Build IPA ( IOS Build )
      # - name: Build IPA
      #  run: flutter build ipa --no-codesign
      # - name: Compress Archives and IPAs
      #   run: |
      #     cd build
      #     tar -czf ios_build.tar.gz ios
      #11 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            # build/ios_build.tar.gz

        #13 Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: ${{ needs.get_version.outputs.version }}
          token: ${{ secrets.TOKEN }}
